//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Vigilant.Utils;

namespace Vigilant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string ServerId { get; set; }
        public bool AllowKick { get; set; }
        public bool AllowMute { get; set; }
        public bool AllowPBan { get; set; }

        private int _pBanNum;
        public int PBanNum
        {
            get { return _pBanNum; }
            set { _pBanNum = Math.Min(1, value); }
        }

        private int _muteNum;
        public int MuteNum
        {
            get { return _muteNum; }
            set { _muteNum = Math.Max(1, value); }
        }

        private int _kickNum;
        public int KickNum
        {
            get { return _kickNum; }
            set { _kickNum = Math.Max(1, value); }
        }

        private int _muteTime;
        public int MuteTime
        {
            get { return _muteTime; }
            set { _muteNum = Math.Max(1, value); }
        }

        private int _blockNum;
        public int BlockNum
        {
            get { return _blockNum; }
            set { _blockNum = Math.Max(1, value); }
        }

        public bool Global { get; set; }
    }
}
