//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vigilant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string ServerId { get; set; }
        public bool AllowKick { get; set; }
        public bool AllowMute { get; set; }
        public bool AllowPBan { get; set; }
        public int PBanNum { get; set; }
        public int MuteNum { get; set; }
        public int KickNum { get; set; }
        public int MuteTime { get; set; }
        public int BlockNum { get; set; }
        public bool Global { get; set; }
    }
}
