//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vigilant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VigilantDbEntities : DbContext
    {
        public VigilantDbEntities()
            : base("name=VigilantDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<ExemptRole> ExemptRoles { get; set; }
        public virtual DbSet<Ignore> Ignores { get; set; }
        public virtual DbSet<Mute> Mutes { get; set; }
        public virtual DbSet<Strike> Strikes { get; set; }
    }
}
